twig:
    default_path: '%kernel.project_dir%/templates'
    # ligne à enlever si on veut retirer le bootstrap
    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
